url: "https://xinglong-zhang.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

title:
  - Xinglong Zhang | University of Oxford

description:
  - Xinglong Zhang's webpage

author:
  - xinglong zhang

